# Basic
title: Shun Zhang
who: Shun Zhang
subtitle: Senior @ Fudan University
welcome_message: <a href="/message" target="_self"><u>Leave a message</u></a>
welcome_description: 留言板
description: Welcome to my personal site.</br>欢迎来到我的个人博客</br>Feel free to look around. 
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 博客主页

# Navigation buttons in the front page.
nav:
    - {title: About Me, description: 关于我, url: '/about'}
    - {title: Projects, description: 我的项目, url: '/projects'}
    - {title: Resume, description: 我的简历, url: '/resume'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: shun-blog
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    linkedin: shun-zhang-08868a158
    github: zhangshun97
    twitter: ShunZhang6
    facebook: shun.zhang.96995
    # gplus: 107108267983477358170
    mail: shunzhang97@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
